name: ligo
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Base
  - python=3.11
  - pip=25.0
  - numpy=1.24
  - scipy=1.12
  - pandas=2.2
  - matplotlib=3.10
  - wget=1.21
  # Jupyter
  - jupyter=1.1
  - ipykernel=6.29
  # sSpecifics
  - astropy=7.0
  - bilby=2.4
  - corner=2.2
  - dynesty=2.1
  - gwosc=0.7
  - gwpy=3.0
  - h5py=3.12
  - lalsuite=7.25
  - ligo.skymap=2.1
  - pycbc=2.4
  - pygcn=1.0
  - pesummary=1.3
  - gwpopulation=0.10
  - nestle=0.2
  # Compatibility
  - decorator=5.1
